HOSTS:
  centos7-master:
    roles:
      - master
      - database
      - dashboard
    platform: el-7-x86_64
    template: centos-7-x86_64
    hypervisor: vcloud
  win2012:
    roles:
      - agent
      - default
    platform: windows-2012-x86_64
    template: win-2012-x86_64
    hypervisor: vcloud
CONFIG:
  nfs_server: none
  consoleport: 443
  datastore: instance0
  folder: Delivery/Quality Assurance/FOSS/Dynamic
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  pooling_api: http://vcloud.delivery.puppetlabs.net/
